version: '3.8'

# Для использования переменных: cp production.env .env

services:
  wordpress:
    image: wordpress:6.4-php8.1-apache
    container_name: researched_wordpress
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      # База данных
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: researched_db
      WORDPRESS_DB_USER: researched_user
      WORDPRESS_DB_PASSWORD: researched_password_2024

      # Настройки для researched.xyz/blog
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://researched.xyz/blog');
        define('WP_SITEURL', 'https://researched.xyz/blog');
        define('FORCE_SSL_ADMIN', true);
        define('WP_CACHE', true);
        define('WP_MEMORY_LIMIT', '256M');
        define('DISALLOW_FILE_EDIT', true);
        define('WP_DEBUG', false);

        // SSL за прокси
        if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
            $_SERVER['HTTPS'] = 'on';
        }

    volumes:
      - ./data/html:/var/www/html
      - wordpress_data:/var/www/html/wp-content/uploads

    depends_on:
      - mysql

    networks:
      - researched_network

  mysql:
    image: mysql:8.0
    container_name: researched_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: researched_db
      MYSQL_USER: researched_user
      MYSQL_PASSWORD: researched_password_2024
      MYSQL_ROOT_PASSWORD: researched_password_2024

    volumes:
      - mysql_data:/var/lib/mysql

    command: >
      --default-authentication-plugin=mysql_native_password
      --innodb-buffer-pool-size=128M
      --max-connections=100
      --innodb-log-file-size=64M

    networks:
      - researched_network


volumes:
  mysql_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  researched_network:
    driver: bridge
