version: '3.8'

services:
  wordpress:
    image: wordpress:6.4-php8.1-apache
    container_name: researched_wordpress
    restart: unless-stopped
    depends_on:
      - mysql
      - redis
    ports:
      - 8080:80
    environment:
      WORDPRESS_TABLE_PREFIX: rxz_42_
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: researched_user
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-researched_password_2024}
      WORDPRESS_DB_NAME: researched_db
      WORDPRESS_CONFIG_EXTRA: |
        define('FORCE_SSL_ADMIN', true);
        define('WP_REDIS_HOST', 'redis');
        define('WP_REDIS_PORT', 6379);
        define('WP_CACHE', true);
        define('WP_MEMORY_LIMIT', '256M');
        define('DISALLOW_FILE_EDIT', true);
        define('WP_DEBUG', false);
    volumes:
      - ./data/html:/var/www/html
      - wordpress_data:/var/www/html/wp-content/uploads
    networks:
      - researched_network

  mysql:
    image: mysql:8.0
    container_name: researched_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: researched_db
      MYSQL_USER: researched_user
      MYSQL_PASSWORD: ${DB_PASSWORD:-researched_password_2024}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-researched_root_2024}
    volumes:
      - mysql_data:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --innodb-buffer-pool-size=128M
      --max-connections=100
      --innodb-log-file-size=64M
    networks:
      - researched_network

  redis:
    image: redis:7-alpine
    container_name: researched_redis
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
    networks:
      - researched_network

volumes:
  mysql_data:
  wordpress_data:

networks:
  researched_network:
    driver: bridge
