services:

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    platform: linux/amd64
    volumes:
      - ./data/html:/var/www/html
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: researched
      WORDPRESS_DB_PASSWORD: researched_xyz
      WORDPRESS_DB_NAME: wordpress

  db:
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: researched_xyz
      MYSQL_DATABASE: wordpress
      MYSQL_USER: researched
      MYSQL_PASSWORD: 'researched_xyz'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    restart: always
    links:
      - db:mysql
    ports:
      - "8081:80"
    environment:
      MYSQL_ROOT_PASSWORD: researched_xyz
